fallback = ''

[matching]
'/Code/' = ''
'code-oss' = ''
'firefox' = ''
'emacs' = ''
'/nvim ?\w*/' = ''
'footclient' = ''
'org.telegram.desktop' = ''
'/Fragments/' = ''
'/Transmission/' = ''
'/GIMP/' = ''
'/GNU/' = ''
'virt-manager' = ''
'gnome-boxes' = ''
'/.*LibreOffice.*/' = '󰈬'
'nemo' = ''
'nm-connection-editor' = '󰒍'
'/Archive Manager/' = '󰛫'
'/Bluetooth/' = ''
